# Generated by Django 4.2.13 on 2024-06-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('image', models.ImageField(upload_to='agency/pictures_in_slider/', verbose_name='image')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'picture',
                'verbose_name_plural': 'pictures',
                'ordering': ['my_order'],
            },
        ),
    ]
